FROM arm32v7/node:10-stretch

COPY qemu-arm-static /usr/bin/

RUN mkdir -p /usr/src/trudesk

COPY . /usr/src/trudesk

WORKDIR /usr/src/trudesk

RUN npm config set unsafe-perm true

RUN apt-get update
RUN apt-get install -y build-essential python

RUN npm install --build-from-source && \
    npm run build && \
    apt-get -y remove build-essential python && \
    apt-get -y autoremove

EXPOSE 8118

CMD [ "/bin/bash", "/usr/src/trudesk/startup.sh" ]